// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: careerhub/scanner/scanner_grpc/grpc.proto

package scanner_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScannerClient is the client API for Scanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScannerClient interface {
	GetJobPostings(ctx context.Context, in *ScanComplete, opts ...grpc.CallOption) (Scanner_GetJobPostingsClient, error)
	GetSkills(ctx context.Context, in *ScanComplete, opts ...grpc.CallOption) (*Skills, error)
	SetRequiredSkills(ctx context.Context, opts ...grpc.CallOption) (Scanner_SetRequiredSkillsClient, error)
	SetScanComplete(ctx context.Context, in *Skills, opts ...grpc.CallOption) (*BoolResponse, error)
}

type scannerClient struct {
	cc grpc.ClientConnInterface
}

func NewScannerClient(cc grpc.ClientConnInterface) ScannerClient {
	return &scannerClient{cc}
}

func (c *scannerClient) GetJobPostings(ctx context.Context, in *ScanComplete, opts ...grpc.CallOption) (Scanner_GetJobPostingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Scanner_ServiceDesc.Streams[0], "/careerhub.scanner.scanner_grpc.Scanner/GetJobPostings", opts...)
	if err != nil {
		return nil, err
	}
	x := &scannerGetJobPostingsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Scanner_GetJobPostingsClient interface {
	Recv() (*JobPostingInfo, error)
	grpc.ClientStream
}

type scannerGetJobPostingsClient struct {
	grpc.ClientStream
}

func (x *scannerGetJobPostingsClient) Recv() (*JobPostingInfo, error) {
	m := new(JobPostingInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *scannerClient) GetSkills(ctx context.Context, in *ScanComplete, opts ...grpc.CallOption) (*Skills, error) {
	out := new(Skills)
	err := c.cc.Invoke(ctx, "/careerhub.scanner.scanner_grpc.Scanner/GetSkills", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scannerClient) SetRequiredSkills(ctx context.Context, opts ...grpc.CallOption) (Scanner_SetRequiredSkillsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Scanner_ServiceDesc.Streams[1], "/careerhub.scanner.scanner_grpc.Scanner/SetRequiredSkills", opts...)
	if err != nil {
		return nil, err
	}
	x := &scannerSetRequiredSkillsClient{stream}
	return x, nil
}

type Scanner_SetRequiredSkillsClient interface {
	Send(*SetRequiredSkillsRequest) error
	CloseAndRecv() (*BoolResponse, error)
	grpc.ClientStream
}

type scannerSetRequiredSkillsClient struct {
	grpc.ClientStream
}

func (x *scannerSetRequiredSkillsClient) Send(m *SetRequiredSkillsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *scannerSetRequiredSkillsClient) CloseAndRecv() (*BoolResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(BoolResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *scannerClient) SetScanComplete(ctx context.Context, in *Skills, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/careerhub.scanner.scanner_grpc.Scanner/SetScanComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScannerServer is the server API for Scanner service.
// All implementations must embed UnimplementedScannerServer
// for forward compatibility
type ScannerServer interface {
	GetJobPostings(*ScanComplete, Scanner_GetJobPostingsServer) error
	GetSkills(context.Context, *ScanComplete) (*Skills, error)
	SetRequiredSkills(Scanner_SetRequiredSkillsServer) error
	SetScanComplete(context.Context, *Skills) (*BoolResponse, error)
	mustEmbedUnimplementedScannerServer()
}

// UnimplementedScannerServer must be embedded to have forward compatible implementations.
type UnimplementedScannerServer struct {
}

func (UnimplementedScannerServer) GetJobPostings(*ScanComplete, Scanner_GetJobPostingsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetJobPostings not implemented")
}
func (UnimplementedScannerServer) GetSkills(context.Context, *ScanComplete) (*Skills, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkills not implemented")
}
func (UnimplementedScannerServer) SetRequiredSkills(Scanner_SetRequiredSkillsServer) error {
	return status.Errorf(codes.Unimplemented, "method SetRequiredSkills not implemented")
}
func (UnimplementedScannerServer) SetScanComplete(context.Context, *Skills) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetScanComplete not implemented")
}
func (UnimplementedScannerServer) mustEmbedUnimplementedScannerServer() {}

// UnsafeScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScannerServer will
// result in compilation errors.
type UnsafeScannerServer interface {
	mustEmbedUnimplementedScannerServer()
}

func RegisterScannerServer(s grpc.ServiceRegistrar, srv ScannerServer) {
	s.RegisterService(&Scanner_ServiceDesc, srv)
}

func _Scanner_GetJobPostings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanComplete)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScannerServer).GetJobPostings(m, &scannerGetJobPostingsServer{stream})
}

type Scanner_GetJobPostingsServer interface {
	Send(*JobPostingInfo) error
	grpc.ServerStream
}

type scannerGetJobPostingsServer struct {
	grpc.ServerStream
}

func (x *scannerGetJobPostingsServer) Send(m *JobPostingInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _Scanner_GetSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanComplete)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).GetSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.scanner.scanner_grpc.Scanner/GetSkills",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).GetSkills(ctx, req.(*ScanComplete))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scanner_SetRequiredSkills_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScannerServer).SetRequiredSkills(&scannerSetRequiredSkillsServer{stream})
}

type Scanner_SetRequiredSkillsServer interface {
	SendAndClose(*BoolResponse) error
	Recv() (*SetRequiredSkillsRequest, error)
	grpc.ServerStream
}

type scannerSetRequiredSkillsServer struct {
	grpc.ServerStream
}

func (x *scannerSetRequiredSkillsServer) SendAndClose(m *BoolResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *scannerSetRequiredSkillsServer) Recv() (*SetRequiredSkillsRequest, error) {
	m := new(SetRequiredSkillsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Scanner_SetScanComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Skills)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScannerServer).SetScanComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/careerhub.scanner.scanner_grpc.Scanner/SetScanComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScannerServer).SetScanComplete(ctx, req.(*Skills))
	}
	return interceptor(ctx, in, info, handler)
}

// Scanner_ServiceDesc is the grpc.ServiceDesc for Scanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "careerhub.scanner.scanner_grpc.Scanner",
	HandlerType: (*ScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSkills",
			Handler:    _Scanner_GetSkills_Handler,
		},
		{
			MethodName: "SetScanComplete",
			Handler:    _Scanner_SetScanComplete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetJobPostings",
			Handler:       _Scanner_GetJobPostings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetRequiredSkills",
			Handler:       _Scanner_SetRequiredSkills_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "careerhub/scanner/scanner_grpc/grpc.proto",
}
